\author[Курс <<Спецглавы математики>>, ФЛА НГТУ]{ {\em Верещагин Антон Сергеевич}
	\\
	канд. физ.-мат. наук, доцент\\
	\bigskip
	Кафедра аэрогидродинамики ФЛА НГТУ
}

\date[]{
	\begin{columns}
	\begin{column}{0.5\textwidth}
	\parbox{\textwidth}{
		\flushright
		QR-код презентации
	}	
	\end{column}
	\begin{column}{0.5\textwidth}
		\centering			
		\includegraphics[width=0.5\textwidth]{../img/qr.pdf}
	\end{column}
	\end{columns}

%	\bigskip
	\bigskip
	\today
}